version: '3'
services:
  mysql:
    build: docker/mysql
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    #    ports:
    #      - '33060:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdf
      MYSQL_DATABASE: zeu
  php:
    build: docker/php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    #      - ./web/uploads:/app/web/uploads
    ports:
      - '8000:80'
    environment:
      PHP_ENABLE_XDEBUG: 1
#    environment:
#      - PHP_USER_ID=1000